// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: validate_rid.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RidToken      string                 `protobuf:"bytes,1,opt,name=rid_token,json=ridToken,proto3" json:"rid_token,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRIDRequest) Reset() {
	*x = ValidateRIDRequest{}
	mi := &file_validate_rid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRIDRequest) ProtoMessage() {}

func (x *ValidateRIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validate_rid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRIDRequest.ProtoReflect.Descriptor instead.
func (*ValidateRIDRequest) Descriptor() ([]byte, []int) {
	return file_validate_rid_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRIDRequest) GetRidToken() string {
	if x != nil {
		return x.RidToken
	}
	return ""
}

func (x *ValidateRIDRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ValidateRIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRIDResponse) Reset() {
	*x = ValidateRIDResponse{}
	mi := &file_validate_rid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRIDResponse) ProtoMessage() {}

func (x *ValidateRIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validate_rid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRIDResponse.ProtoReflect.Descriptor instead.
func (*ValidateRIDResponse) Descriptor() ([]byte, []int) {
	return file_validate_rid_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRIDResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateRIDResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_validate_rid_proto protoreflect.FileDescriptor

const file_validate_rid_proto_rawDesc = "" +
	"\n" +
	"\x12validate_rid.proto\x12\rreplayapi_iam\"T\n" +
	"\x12ValidateRIDRequest\x12\x1b\n" +
	"\trid_token\x18\x01 \x01(\tR\bridToken\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"H\n" +
	"\x13ValidateRIDResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2b\n" +
	"\n" +
	"RIDService\x12T\n" +
	"\vValidateRID\x12!.replayapi_iam.ValidateRIDRequest\x1a\".replayapi_iam.ValidateRIDResponseB\x13Z\x11generated/iam;iamb\x06proto3"

var (
	file_validate_rid_proto_rawDescOnce sync.Once
	file_validate_rid_proto_rawDescData []byte
)

func file_validate_rid_proto_rawDescGZIP() []byte {
	file_validate_rid_proto_rawDescOnce.Do(func() {
		file_validate_rid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validate_rid_proto_rawDesc), len(file_validate_rid_proto_rawDesc)))
	})
	return file_validate_rid_proto_rawDescData
}

var file_validate_rid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_validate_rid_proto_goTypes = []any{
	(*ValidateRIDRequest)(nil),  // 0: replayapi_iam.ValidateRIDRequest
	(*ValidateRIDResponse)(nil), // 1: replayapi_iam.ValidateRIDResponse
}
var file_validate_rid_proto_depIdxs = []int32{
	0, // 0: replayapi_iam.RIDService.ValidateRID:input_type -> replayapi_iam.ValidateRIDRequest
	1, // 1: replayapi_iam.RIDService.ValidateRID:output_type -> replayapi_iam.ValidateRIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_rid_proto_init() }
func file_validate_rid_proto_init() {
	if File_validate_rid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_rid_proto_rawDesc), len(file_validate_rid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validate_rid_proto_goTypes,
		DependencyIndexes: file_validate_rid_proto_depIdxs,
		MessageInfos:      file_validate_rid_proto_msgTypes,
	}.Build()
	File_validate_rid_proto = out.File
	file_validate_rid_proto_goTypes = nil
	file_validate_rid_proto_depIdxs = nil
}
