// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: validate_rid.proto

package iam

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RIDService_ValidateRID_FullMethodName = "/replayapi_iam.RIDService/ValidateRID"
)

// RIDServiceClient is the client API for RIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RIDServiceClient interface {
	ValidateRID(ctx context.Context, in *ValidateRIDRequest, opts ...grpc.CallOption) (*ValidateRIDResponse, error)
}

type rIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRIDServiceClient(cc grpc.ClientConnInterface) RIDServiceClient {
	return &rIDServiceClient{cc}
}

func (c *rIDServiceClient) ValidateRID(ctx context.Context, in *ValidateRIDRequest, opts ...grpc.CallOption) (*ValidateRIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRIDResponse)
	err := c.cc.Invoke(ctx, RIDService_ValidateRID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}