// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: calendar.proto

package squad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	SquadIds      []string               `protobuf:"bytes,3,rep,name=squad_ids,json=squadIds,proto3" json:"squad_ids,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,4,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Region        string                 `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Passphrase    string                 `protobuf:"bytes,12,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Type          string                 `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	GameId        string                 `protobuf:"bytes,14,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Status        string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	Url           string                 `protobuf:"bytes,16,opt,name=url,proto3" json:"url,omitempty"`
	LogoUri       string                 `protobuf:"bytes,17,opt,name=logo_uri,json=logoUri,proto3" json:"logo_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarEvent) Reset() {
	*x = CalendarEvent{}
	mi := &file_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarEvent) ProtoMessage() {}

func (x *CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarEvent.ProtoReflect.Descriptor instead.
func (*CalendarEvent) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalendarEvent) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *CalendarEvent) GetSquadIds() []string {
	if x != nil {
		return x.SquadIds
	}
	return nil
}

func (x *CalendarEvent) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *CalendarEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CalendarEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CalendarEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CalendarEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CalendarEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CalendarEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CalendarEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CalendarEvent) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *CalendarEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CalendarEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CalendarEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CalendarEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CalendarEvent) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

var File_calendar_proto protoreflect.FileDescriptor

const file_calendar_proto_rawDesc = "" +
	"\n" +
	"\x0ecalendar.proto\x12\x18replayapi_squad_calendar\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x04\n" +
	"\rCalendarEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x1b\n" +
	"\tsquad_ids\x18\x03 \x03(\tR\bsquadIds\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x04 \x03(\tR\tplayerIds\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x16\n" +
	"\x06region\x18\v \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"passphrase\x18\f \x01(\tR\n" +
	"passphrase\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\x12\x17\n" +
	"\agame_id\x18\x0e \x01(\tR\x06gameId\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x10\n" +
	"\x03url\x18\x10 \x01(\tR\x03url\x12\x19\n" +
	"\blogo_uri\x18\x11 \x01(\tR\alogoUriB\x17Z\x15generated/squad;squadb\x06proto3"

var (
	file_calendar_proto_rawDescOnce sync.Once
	file_calendar_proto_rawDescData []byte
)

func file_calendar_proto_rawDescGZIP() []byte {
	file_calendar_proto_rawDescOnce.Do(func() {
		file_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)))
	})
	return file_calendar_proto_rawDescData
}

var file_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_calendar_proto_goTypes = []any{
	(*CalendarEvent)(nil),         // 0: replayapi_squad_calendar.CalendarEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_calendar_proto_depIdxs = []int32{
	1, // 0: replayapi_squad_calendar.CalendarEvent.start_time:type_name -> google.protobuf.Timestamp
	1, // 1: replayapi_squad_calendar.CalendarEvent.end_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_calendar_proto_init() }
func file_calendar_proto_init() {
	if File_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calendar_proto_goTypes,
		DependencyIndexes: file_calendar_proto_depIdxs,
		MessageInfos:      file_calendar_proto_msgTypes,
	}.Build()
	File_calendar_proto = out.File
	file_calendar_proto_goTypes = nil
	file_calendar_proto_depIdxs = nil
}
