// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: player_profile.proto

package squad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	SlugUri       string                 `protobuf:"bytes,4,opt,name=slug_uri,json=slugUri,proto3" json:"slug_uri,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarUri     string                 `protobuf:"bytes,6,opt,name=avatar_uri,json=avatarUri,proto3" json:"avatar_uri,omitempty"`
	Roles         []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Squads        []*SquadMembership     `protobuf:"bytes,10,rep,name=squads,proto3" json:"squads,omitempty"`
	Networks      []string               `protobuf:"bytes,11,rep,name=networks,proto3" json:"networks,omitempty"`
	Regions       []string               `protobuf:"bytes,12,rep,name=regions,proto3" json:"regions,omitempty"`
	Languages     []string               `protobuf:"bytes,13,rep,name=languages,proto3" json:"languages,omitempty"`
	Genre         []string               `protobuf:"bytes,14,rep,name=genre,proto3" json:"genre,omitempty"`
	Tags          []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Score         []string               `protobuf:"bytes,16,rep,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	mi := &file_player_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_player_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_player_profile_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerProfile) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerProfile) GetSlugUri() string {
	if x != nil {
		return x.SlugUri
	}
	return ""
}

func (x *PlayerProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerProfile) GetAvatarUri() string {
	if x != nil {
		return x.AvatarUri
	}
	return ""
}

func (x *PlayerProfile) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PlayerProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlayerProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PlayerProfile) GetSquads() []*SquadMembership {
	if x != nil {
		return x.Squads
	}
	return nil
}

func (x *PlayerProfile) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *PlayerProfile) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *PlayerProfile) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *PlayerProfile) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *PlayerProfile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PlayerProfile) GetScore() []string {
	if x != nil {
		return x.Score
	}
	return nil
}

type SquadMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SquadId       string                 `protobuf:"bytes,1,opt,name=squad_id,json=squadId,proto3" json:"squad_id,omitempty"`
	SquadName     string                 `protobuf:"bytes,2,opt,name=squad_name,json=squadName,proto3" json:"squad_name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SlugUri       string                 `protobuf:"bytes,4,opt,name=slug_uri,json=slugUri,proto3" json:"slug_uri,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SquadMembership) Reset() {
	*x = SquadMembership{}
	mi := &file_player_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquadMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquadMembership) ProtoMessage() {}

func (x *SquadMembership) ProtoReflect() protoreflect.Message {
	mi := &file_player_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquadMembership.ProtoReflect.Descriptor instead.
func (*SquadMembership) Descriptor() ([]byte, []int) {
	return file_player_profile_proto_rawDescGZIP(), []int{1}
}

func (x *SquadMembership) GetSquadId() string {
	if x != nil {
		return x.SquadId
	}
	return ""
}

func (x *SquadMembership) GetSquadName() string {
	if x != nil {
		return x.SquadName
	}
	return ""
}

func (x *SquadMembership) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SquadMembership) GetSlugUri() string {
	if x != nil {
		return x.SlugUri
	}
	return ""
}

func (x *SquadMembership) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SquadMembership) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetPlayerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RidToken      string                 `protobuf:"bytes,2,opt,name=rid_token,json=ridToken,proto3" json:"rid_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerProfileRequest) Reset() {
	*x = GetPlayerProfileRequest{}
	mi := &file_player_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerProfileRequest) ProtoMessage() {}

func (x *GetPlayerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerProfileRequest) Descriptor() ([]byte, []int) {
	return file_player_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerProfileRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerProfileRequest) GetRidToken() string {
	if x != nil {
		return x.RidToken
	}
	return ""
}

type GetPlayerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	PlayerProfile *PlayerProfile         `protobuf:"bytes,3,opt,name=player_profile,json=playerProfile,proto3" json:"player_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerProfileResponse) Reset() {
	*x = GetPlayerProfileResponse{}
	mi := &file_player_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerProfileResponse) ProtoMessage() {}

func (x *GetPlayerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerProfileResponse) Descriptor() ([]byte, []int) {
	return file_player_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerProfileResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *GetPlayerProfileResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetPlayerProfileResponse) GetPlayerProfile() *PlayerProfile {
	if x != nil {
		return x.PlayerProfile
	}
	return nil
}

var File_player_profile_proto protoreflect.FileDescriptor

const file_player_profile_proto_rawDesc = "" +
	"\n" +
	"\x14player_profile.proto\x12\x18replayapi_player_profile\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x04\n" +
	"\rPlayerProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x19\n" +
	"\bslug_uri\x18\x04 \x01(\tR\aslugUri\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"avatar_uri\x18\x06 \x01(\tR\tavatarUri\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x06squads\x18\n" +
	" \x03(\v2).replayapi_player_profile.SquadMembershipR\x06squads\x12\x1a\n" +
	"\bnetworks\x18\v \x03(\tR\bnetworks\x12\x18\n" +
	"\aregions\x18\f \x03(\tR\aregions\x12\x1c\n" +
	"\tlanguages\x18\r \x03(\tR\tlanguages\x12\x14\n" +
	"\x05genre\x18\x0e \x03(\tR\x05genre\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\x12\x14\n" +
	"\x05score\x18\x10 \x03(\tR\x05score\"\xa8\x01\n" +
	"\x0fSquadMembership\x12\x19\n" +
	"\bsquad_id\x18\x01 \x01(\tR\asquadId\x12\x1d\n" +
	"\n" +
	"squad_name\x18\x02 \x01(\tR\tsquadName\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x19\n" +
	"\bslug_uri\x18\x04 \x01(\tR\aslugUri\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\"S\n" +
	"\x17GetPlayerProfileRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\trid_token\x18\x02 \x01(\tR\bridToken\"\x9d\x01\n" +
	"\x18GetPlayerProfileResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12N\n" +
	"\x0eplayer_profile\x18\x03 \x01(\v2'.replayapi_player_profile.PlayerProfileR\rplayerProfile2\x91\x01\n" +
	"\x14PlayerProfileService\x12y\n" +
	"\x10GetPlayerProfile\x121.replayapi_player_profile.GetPlayerProfileRequest\x1a2.replayapi_player_profile.GetPlayerProfileResponseB\x17Z\x15generated/squad;squadb\x06proto3"

var (
	file_player_profile_proto_rawDescOnce sync.Once
	file_player_profile_proto_rawDescData []byte
)

func file_player_profile_proto_rawDescGZIP() []byte {
	file_player_profile_proto_rawDescOnce.Do(func() {
		file_player_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_profile_proto_rawDesc), len(file_player_profile_proto_rawDesc)))
	})
	return file_player_profile_proto_rawDescData
}

var file_player_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_player_profile_proto_goTypes = []any{
	(*PlayerProfile)(nil),            // 0: replayapi_player_profile.PlayerProfile
	(*SquadMembership)(nil),          // 1: replayapi_player_profile.SquadMembership
	(*GetPlayerProfileRequest)(nil),  // 2: replayapi_player_profile.GetPlayerProfileRequest
	(*GetPlayerProfileResponse)(nil), // 3: replayapi_player_profile.GetPlayerProfileResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_player_profile_proto_depIdxs = []int32{
	4, // 0: replayapi_player_profile.PlayerProfile.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: replayapi_player_profile.PlayerProfile.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: replayapi_player_profile.PlayerProfile.squads:type_name -> replayapi_player_profile.SquadMembership
	0, // 3: replayapi_player_profile.GetPlayerProfileResponse.player_profile:type_name -> replayapi_player_profile.PlayerProfile
	2, // 4: replayapi_player_profile.PlayerProfileService.GetPlayerProfile:input_type -> replayapi_player_profile.GetPlayerProfileRequest
	3, // 5: replayapi_player_profile.PlayerProfileService.GetPlayerProfile:output_type -> replayapi_player_profile.GetPlayerProfileResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_player_profile_proto_init() }
func file_player_profile_proto_init() {
	if File_player_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_profile_proto_rawDesc), len(file_player_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_profile_proto_goTypes,
		DependencyIndexes: file_player_profile_proto_depIdxs,
		MessageInfos:      file_player_profile_proto_msgTypes,
	}.Build()
	File_player_profile_proto = out.File
	file_player_profile_proto_goTypes = nil
	file_player_profile_proto_depIdxs = nil
}
