// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: player_profile.proto

package squad

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerProfileService_GetPlayerProfile_FullMethodName = "/replayapi_player_profile.PlayerProfileService/GetPlayerProfile"
)

// PlayerProfileServiceClient is the client API for PlayerProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerProfileServiceClient interface {
	GetPlayerProfile(ctx context.Context, in *GetPlayerProfileRequest, opts ...grpc.CallOption) (*GetPlayerProfileResponse, error)
}

type playerProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerProfileServiceClient(cc grpc.ClientConnInterface) PlayerProfileServiceClient {
	return &playerProfileServiceClient{cc}
}

func (c *playerProfileServiceClient) GetPlayerProfile(ctx context.Context, in *GetPlayerProfileRequest, opts ...grpc.CallOption) (*GetPlayerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerProfileResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_GetPlayerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}