// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: subscription.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionService_GetSubscription_FullMethodName   = "/replayapi_billing.SubscriptionService/GetSubscription"
	SubscriptionService_ValidateOperation_FullMethodName = "/replayapi_billing.SubscriptionService/ValidateOperation"
	SubscriptionService_ConfirmOperation_FullMethodName  = "/replayapi_billing.SubscriptionService/ConfirmOperation"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	ValidateOperation(ctx context.Context, in *ValidateOperationRequest, opts ...grpc.CallOption) (*ValidateOperationResponse, error)
	ConfirmOperation(ctx context.Context, in *ConfirmOperationRequest, opts ...grpc.CallOption) (*ConfirmOperationResponse, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ValidateOperation(ctx context.Context, in *ValidateOperationRequest, opts ...grpc.CallOption) (*ValidateOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOperationResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_ValidateOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ConfirmOperation(ctx context.Context, in *ConfirmOperationRequest, opts ...grpc.CallOption) (*ConfirmOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmOperationResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_ConfirmOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}