// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: subscription.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Usage         map[string]int32       `protobuf:"bytes,6,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Available     map[string]int32       `protobuf:"bytes,7,rep,name=available,proto3" json:"available,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Subscription) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetUsage() map[string]int32 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Subscription) GetAvailable() map[string]int32 {
	if x != nil {
		return x.Available
	}
	return nil
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RidToken      string                 `protobuf:"bytes,2,opt,name=rid_token,json=ridToken,proto3" json:"rid_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSubscriptionRequest) GetRidToken() string {
	if x != nil {
		return x.RidToken
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Subscription  *Subscription          `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *GetSubscriptionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type ValidateOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RidToken      string                 `protobuf:"bytes,2,opt,name=rid_token,json=ridToken,proto3" json:"rid_token,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOperationRequest) Reset() {
	*x = ValidateOperationRequest{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOperationRequest) ProtoMessage() {}

func (x *ValidateOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOperationRequest.ProtoReflect.Descriptor instead.
func (*ValidateOperationRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateOperationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateOperationRequest) GetRidToken() string {
	if x != nil {
		return x.RidToken
	}
	return ""
}

func (x *ValidateOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ValidateOperationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ValidateOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOperationResponse) Reset() {
	*x = ValidateOperationResponse{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOperationResponse) ProtoMessage() {}

func (x *ValidateOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOperationResponse.ProtoReflect.Descriptor instead.
func (*ValidateOperationResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateOperationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateOperationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfirmOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RidToken      string                 `protobuf:"bytes,2,opt,name=rid_token,json=ridToken,proto3" json:"rid_token,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOperationRequest) Reset() {
	*x = ConfirmOperationRequest{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOperationRequest) ProtoMessage() {}

func (x *ConfirmOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOperationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOperationRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmOperationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmOperationRequest) GetRidToken() string {
	if x != nil {
		return x.RidToken
	}
	return ""
}

func (x *ConfirmOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ConfirmOperationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConfirmOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOperationResponse) Reset() {
	*x = ConfirmOperationResponse{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOperationResponse) ProtoMessage() {}

func (x *ConfirmOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOperationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmOperationResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmOperationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x11replayapi_billing\"\x9a\x03\n" +
	"\fSubscription\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12@\n" +
	"\x05usage\x18\x06 \x03(\v2*.replayapi_billing.Subscription.UsageEntryR\x05usage\x12L\n" +
	"\tavailable\x18\a \x03(\v2..replayapi_billing.Subscription.AvailableEntryR\tavailable\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eAvailableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"N\n" +
	"\x16GetSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trid_token\x18\x02 \x01(\tR\bridToken\"\x91\x01\n" +
	"\x17GetSubscriptionResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12C\n" +
	"\fsubscription\x18\x03 \x01(\v2\x1f.replayapi_billing.SubscriptionR\fsubscription\"\x8b\x01\n" +
	"\x18ValidateOperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trid_token\x18\x02 \x01(\tR\bridToken\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\"N\n" +
	"\x19ValidateOperationResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x17ConfirmOperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trid_token\x18\x02 \x01(\tR\bridToken\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\"L\n" +
	"\x18ConfirmOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xdc\x02\n" +
	"\x13SubscriptionService\x12h\n" +
	"\x0fGetSubscription\x12).replayapi_billing.GetSubscriptionRequest\x1a*.replayapi_billing.GetSubscriptionResponse\x12n\n" +
	"\x11ValidateOperation\x12+.replayapi_billing.ValidateOperationRequest\x1a,.replayapi_billing.ValidateOperationResponse\x12k\n" +
	"\x10ConfirmOperation\x12*.replayapi_billing.ConfirmOperationRequest\x1a+.replayapi_billing.ConfirmOperationResponseB\x1bZ\x19generated/billing;billingb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_subscription_proto_goTypes = []any{
	(*Subscription)(nil),              // 0: replayapi_billing.Subscription
	(*GetSubscriptionRequest)(nil),    // 1: replayapi_billing.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),   // 2: replayapi_billing.GetSubscriptionResponse
	(*ValidateOperationRequest)(nil),  // 3: replayapi_billing.ValidateOperationRequest
	(*ValidateOperationResponse)(nil), // 4: replayapi_billing.ValidateOperationResponse
	(*ConfirmOperationRequest)(nil),   // 5: replayapi_billing.ConfirmOperationRequest
	(*ConfirmOperationResponse)(nil),  // 6: replayapi_billing.ConfirmOperationResponse
	nil,                               // 7: replayapi_billing.Subscription.UsageEntry
	nil,                               // 8: replayapi_billing.Subscription.AvailableEntry
}
var file_subscription_proto_depIdxs = []int32{
	7, // 0: replayapi_billing.Subscription.usage:type_name -> replayapi_billing.Subscription.UsageEntry
	8, // 1: replayapi_billing.Subscription.available:type_name -> replayapi_billing.Subscription.AvailableEntry
	0, // 2: replayapi_billing.GetSubscriptionResponse.subscription:type_name -> replayapi_billing.Subscription
	1, // 3: replayapi_billing.SubscriptionService.GetSubscription:input_type -> replayapi_billing.GetSubscriptionRequest
	3, // 4: replayapi_billing.SubscriptionService.ValidateOperation:input_type -> replayapi_billing.ValidateOperationRequest
	5, // 5: replayapi_billing.SubscriptionService.ConfirmOperation:input_type -> replayapi_billing.ConfirmOperationRequest
	2, // 6: replayapi_billing.SubscriptionService.GetSubscription:output_type -> replayapi_billing.GetSubscriptionResponse
	4, // 7: replayapi_billing.SubscriptionService.ValidateOperation:output_type -> replayapi_billing.ValidateOperationResponse
	6, // 8: replayapi_billing.SubscriptionService.ConfirmOperation:output_type -> replayapi_billing.ConfirmOperationResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
