// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/infra/events/schemas/matchmaking_events.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope follows CloudEvents 1.0 spec (https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md).
// Ensures replay-api and match-making-api agree on payload structure.
type EventEnvelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // CloudEvents: id (required) - uniquely identifies the event
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`               // CloudEvents: type (required) - e.g. "PlayerQueued", "MatchCompleted"
	Source      string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`           // CloudEvents: source (required) - e.g. "replay-api", "match-making-api"
	Specversion string                 `protobuf:"bytes,4,opt,name=specversion,proto3" json:"specversion,omitempty"` // CloudEvents: specversion (required) - e.g. "1.0"
	Time        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`               // CloudEvents: time (optional) - when the event occurred
	Subject     string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`         // CloudEvents: subject (optional) - e.g. player_id, match_id
	// Extension attributes
	ResourceOwnerId   string `protobuf:"bytes,7,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`      // RID or owner identifier for multi-tenancy/authorization
	CorrelationId     string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`              // For distributed tracing
	DataschemaVersion int32  `protobuf:"varint,9,opt,name=dataschema_version,json=dataschemaVersion,proto3" json:"dataschema_version,omitempty"` // Payload schema version for evolution; consumers can handle multiple versions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetSpecversion() string {
	if x != nil {
		return x.Specversion
	}
	return ""
}

func (x *EventEnvelope) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EventEnvelope) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventEnvelope) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetDataschemaVersion() int32 {
	if x != nil {
		return x.DataschemaVersion
	}
	return 0
}

// MatchmakingEvent is the top-level message for Kafka. Combines envelope + typed data (CloudEvents: data).
type MatchmakingEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *EventEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MatchmakingEvent_PlayerQueued
	//	*MatchmakingEvent_MatchCreated
	//	*MatchmakingEvent_MatchCompleted
	//	*MatchmakingEvent_RatingsUpdated
	//	*MatchmakingEvent_PlayerLeftQueue
	//	*MatchmakingEvent_PlayerQueueConfirmed
	//	*MatchmakingEvent_ServerAllocated
	//	*MatchmakingEvent_MatchStarted
	//	*MatchmakingEvent_MatchResultsCalculated
	//	*MatchmakingEvent_PrizeDistributed
	//	*MatchmakingEvent_AnalyticsTracked
	Data          isMatchmakingEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingEvent) Reset() {
	*x = MatchmakingEvent{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingEvent) ProtoMessage() {}

func (x *MatchmakingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingEvent.ProtoReflect.Descriptor instead.
func (*MatchmakingEvent) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{1}
}

func (x *MatchmakingEvent) GetEnvelope() *EventEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *MatchmakingEvent) GetData() isMatchmakingEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchmakingEvent) GetPlayerQueued() *PlayerQueuedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_PlayerQueued); ok {
			return x.PlayerQueued
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchCreated() *MatchCreatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchCreated); ok {
			return x.MatchCreated
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchCompleted() *MatchCompletedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchCompleted); ok {
			return x.MatchCompleted
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetRatingsUpdated() *RatingsUpdatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_RatingsUpdated); ok {
			return x.RatingsUpdated
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetPlayerLeftQueue() *PlayerLeftQueuePayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_PlayerLeftQueue); ok {
			return x.PlayerLeftQueue
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetPlayerQueueConfirmed() *PlayerQueueConfirmedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_PlayerQueueConfirmed); ok {
			return x.PlayerQueueConfirmed
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetServerAllocated() *ServerAllocatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_ServerAllocated); ok {
			return x.ServerAllocated
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchStarted() *MatchStartedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchResultsCalculated() *MatchResultsCalculatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchResultsCalculated); ok {
			return x.MatchResultsCalculated
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetPrizeDistributed() *PrizeDistributedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_PrizeDistributed); ok {
			return x.PrizeDistributed
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetAnalyticsTracked() *AnalyticsTrackedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_AnalyticsTracked); ok {
			return x.AnalyticsTracked
		}
	}
	return nil
}

type isMatchmakingEvent_Data interface {
	isMatchmakingEvent_Data()
}

type MatchmakingEvent_PlayerQueued struct {
	PlayerQueued *PlayerQueuedPayload `protobuf:"bytes,10,opt,name=player_queued,json=playerQueued,proto3,oneof"`
}

type MatchmakingEvent_MatchCreated struct {
	MatchCreated *MatchCreatedPayload `protobuf:"bytes,11,opt,name=match_created,json=matchCreated,proto3,oneof"`
}

type MatchmakingEvent_MatchCompleted struct {
	MatchCompleted *MatchCompletedPayload `protobuf:"bytes,12,opt,name=match_completed,json=matchCompleted,proto3,oneof"`
}

type MatchmakingEvent_RatingsUpdated struct {
	RatingsUpdated *RatingsUpdatedPayload `protobuf:"bytes,13,opt,name=ratings_updated,json=ratingsUpdated,proto3,oneof"`
}

type MatchmakingEvent_PlayerLeftQueue struct {
	PlayerLeftQueue *PlayerLeftQueuePayload `protobuf:"bytes,14,opt,name=player_left_queue,json=playerLeftQueue,proto3,oneof"`
}

type MatchmakingEvent_PlayerQueueConfirmed struct {
	PlayerQueueConfirmed *PlayerQueueConfirmedPayload `protobuf:"bytes,15,opt,name=player_queue_confirmed,json=playerQueueConfirmed,proto3,oneof"`
}

type MatchmakingEvent_ServerAllocated struct {
	ServerAllocated *ServerAllocatedPayload `protobuf:"bytes,16,opt,name=server_allocated,json=serverAllocated,proto3,oneof"`
}

type MatchmakingEvent_MatchStarted struct {
	MatchStarted *MatchStartedPayload `protobuf:"bytes,17,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type MatchmakingEvent_MatchResultsCalculated struct {
	MatchResultsCalculated *MatchResultsCalculatedPayload `protobuf:"bytes,18,opt,name=match_results_calculated,json=matchResultsCalculated,proto3,oneof"`
}

type MatchmakingEvent_PrizeDistributed struct {
	PrizeDistributed *PrizeDistributedPayload `protobuf:"bytes,19,opt,name=prize_distributed,json=prizeDistributed,proto3,oneof"`
}

type MatchmakingEvent_AnalyticsTracked struct {
	AnalyticsTracked *AnalyticsTrackedPayload `protobuf:"bytes,20,opt,name=analytics_tracked,json=analyticsTracked,proto3,oneof"`
}

func (*MatchmakingEvent_PlayerQueued) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchCreated) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchCompleted) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_RatingsUpdated) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_PlayerLeftQueue) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_PlayerQueueConfirmed) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_ServerAllocated) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchStarted) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchResultsCalculated) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_PrizeDistributed) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_AnalyticsTracked) isMatchmakingEvent_Data() {}

type AnalyticsTrackedPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MatchId            string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIds          []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	WinnerTeamId       string                 `protobuf:"bytes,3,opt,name=winner_team_id,json=winnerTeamId,proto3" json:"winner_team_id,omitempty"` // Empty if draw.
	IsDraw             bool                   `protobuf:"varint,4,opt,name=is_draw,json=isDraw,proto3" json:"is_draw,omitempty"`
	CompletedAtEpochMs int64                  `protobuf:"varint,5,opt,name=completed_at_epoch_ms,json=completedAtEpochMs,proto3" json:"completed_at_epoch_ms,omitempty"`
	TrackedAtEpochMs   int64                  `protobuf:"varint,6,opt,name=tracked_at_epoch_ms,json=trackedAtEpochMs,proto3" json:"tracked_at_epoch_ms,omitempty"` // When the event was produced (audit).
	DurationMs         int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                       // 0 if unknown; computed from start if available.
	TenantId           string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId           string                 `protobuf:"bytes,9,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourceOwnerId    string                 `protobuf:"bytes,10,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"` // Tenant/client isolation; analytics consumers must respect.
	GameId             string                 `protobuf:"bytes,11,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                              // Optional: for per-game analytics.
	LobbyId            string                 `protobuf:"bytes,12,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`                           // Optional: tournament/lobby reference.
	PrizePoolId        string                 `protobuf:"bytes,13,opt,name=prize_pool_id,json=prizePoolId,proto3" json:"prize_pool_id,omitempty"`             // Optional: prize pool reference.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalyticsTrackedPayload) Reset() {
	*x = AnalyticsTrackedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsTrackedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsTrackedPayload) ProtoMessage() {}

func (x *AnalyticsTrackedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsTrackedPayload.ProtoReflect.Descriptor instead.
func (*AnalyticsTrackedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyticsTrackedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *AnalyticsTrackedPayload) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

func (x *AnalyticsTrackedPayload) GetCompletedAtEpochMs() int64 {
	if x != nil {
		return x.CompletedAtEpochMs
	}
	return 0
}

func (x *AnalyticsTrackedPayload) GetTrackedAtEpochMs() int64 {
	if x != nil {
		return x.TrackedAtEpochMs
	}
	return 0
}

func (x *AnalyticsTrackedPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AnalyticsTrackedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *AnalyticsTrackedPayload) GetPrizePoolId() string {
	if x != nil {
		return x.PrizePoolId
	}
	return ""
}

type MatchStartedPayload struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MatchId               string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ResourceOwnerId       string                 `protobuf:"bytes,2,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`
	PlayerIds             []string               `protobuf:"bytes,3,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`                                                // Players to receive MatchStarted notification.
	CountdownSeconds      *int32                 `protobuf:"varint,4,opt,name=countdown_seconds,json=countdownSeconds,proto3,oneof" json:"countdown_seconds,omitempty"`                    // Countdown duration (if applicable).
	StartTimestampEpochMs *int64                 `protobuf:"varint,5,opt,name=start_timestamp_epoch_ms,json=startTimestampEpochMs,proto3,oneof" json:"start_timestamp_epoch_ms,omitempty"` // When match starts/started.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MatchStartedPayload) Reset() {
	*x = MatchStartedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartedPayload) ProtoMessage() {}

func (x *MatchStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartedPayload.ProtoReflect.Descriptor instead.
func (*MatchStartedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{3}
}

func (x *MatchStartedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchStartedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *MatchStartedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchStartedPayload) GetCountdownSeconds() int32 {
	if x != nil && x.CountdownSeconds != nil {
		return *x.CountdownSeconds
	}
	return 0
}

func (x *MatchStartedPayload) GetStartTimestampEpochMs() int64 {
	if x != nil && x.StartTimestampEpochMs != nil {
		return *x.StartTimestampEpochMs
	}
	return 0
}

type ServerAllocatedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchId         string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerId        string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Region          string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	ResourceOwnerId string                 `protobuf:"bytes,4,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`
	PlayerIds       []string               `protobuf:"bytes,5,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`                         // Players to receive MatchReady; from MatchCreated.
	ConnectionUrl   *string                `protobuf:"bytes,6,opt,name=connection_url,json=connectionUrl,proto3,oneof" json:"connection_url,omitempty"`       // Optional: URL or token reference for connection.
	ConnectionToken *string                `protobuf:"bytes,7,opt,name=connection_token,json=connectionToken,proto3,oneof" json:"connection_token,omitempty"` // Optional: short-lived token for auth.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerAllocatedPayload) Reset() {
	*x = ServerAllocatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAllocatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAllocatedPayload) ProtoMessage() {}

func (x *ServerAllocatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAllocatedPayload.ProtoReflect.Descriptor instead.
func (*ServerAllocatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{4}
}

func (x *ServerAllocatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ServerAllocatedPayload) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerAllocatedPayload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerAllocatedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *ServerAllocatedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *ServerAllocatedPayload) GetConnectionUrl() string {
	if x != nil && x.ConnectionUrl != nil {
		return *x.ConnectionUrl
	}
	return ""
}

func (x *ServerAllocatedPayload) GetConnectionToken() string {
	if x != nil && x.ConnectionToken != nil {
		return *x.ConnectionToken
	}
	return ""
}

type PlayerQueueConfirmedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId          string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Region          string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Position        int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`                       // Queue position (1-based). 0 if match found immediately.
	EtaSeconds      int32                  `protobuf:"varint,5,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"` // Best-effort estimated wait in seconds. 0 if match found.
	TenantId        string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourceOwnerId string                 `protobuf:"bytes,8,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"` // From envelope; included for convenience.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerQueueConfirmedPayload) Reset() {
	*x = PlayerQueueConfirmedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQueueConfirmedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQueueConfirmedPayload) ProtoMessage() {}

func (x *PlayerQueueConfirmedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQueueConfirmedPayload.ProtoReflect.Descriptor instead.
func (*PlayerQueueConfirmedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerQueueConfirmedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerQueueConfirmedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerQueueConfirmedPayload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlayerQueueConfirmedPayload) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlayerQueueConfirmedPayload) GetEtaSeconds() int32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *PlayerQueueConfirmedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlayerQueueConfirmedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlayerQueueConfirmedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

type PlayerQueuedPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId              string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Region              string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	SkillRange          *SkillRange            `protobuf:"bytes,4,opt,name=skill_range,json=skillRange,proto3,oneof" json:"skill_range,omitempty"`           // Optional: min/max MMR or similar.
	PriorityBoost       *int32                 `protobuf:"varint,5,opt,name=priority_boost,json=priorityBoost,proto3,oneof" json:"priority_boost,omitempty"` // Optional: queue priority.
	TenantId            string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourcePermissions []string               `protobuf:"bytes,8,rep,name=resource_permissions,json=resourcePermissions,proto3" json:"resource_permissions,omitempty"` // Optional: e.g. ["read", "write"].
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerQueuedPayload) Reset() {
	*x = PlayerQueuedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQueuedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQueuedPayload) ProtoMessage() {}

func (x *PlayerQueuedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQueuedPayload.ProtoReflect.Descriptor instead.
func (*PlayerQueuedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerQueuedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlayerQueuedPayload) GetSkillRange() *SkillRange {
	if x != nil {
		return x.SkillRange
	}
	return nil
}

func (x *PlayerQueuedPayload) GetPriorityBoost() int32 {
	if x != nil && x.PriorityBoost != nil {
		return *x.PriorityBoost
	}
	return 0
}

func (x *PlayerQueuedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetResourcePermissions() []string {
	if x != nil {
		return x.ResourcePermissions
	}
	return nil
}

type SkillRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinMmr        int32                  `protobuf:"varint,1,opt,name=min_mmr,json=minMmr,proto3" json:"min_mmr,omitempty"`
	MaxMmr        int32                  `protobuf:"varint,2,opt,name=max_mmr,json=maxMmr,proto3" json:"max_mmr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRange) Reset() {
	*x = SkillRange{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRange) ProtoMessage() {}

func (x *SkillRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRange.ProtoReflect.Descriptor instead.
func (*SkillRange) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{7}
}

func (x *SkillRange) GetMinMmr() int32 {
	if x != nil {
		return x.MinMmr
	}
	return 0
}

func (x *SkillRange) GetMaxMmr() int32 {
	if x != nil {
		return x.MaxMmr
	}
	return 0
}

type PlayerLeftQueuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"` // Optional: e.g. "user_cancelled", "timeout", "disconnect"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftQueuePayload) Reset() {
	*x = PlayerLeftQueuePayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftQueuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftQueuePayload) ProtoMessage() {}

func (x *PlayerLeftQueuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftQueuePayload.ProtoReflect.Descriptor instead.
func (*PlayerLeftQueuePayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerLeftQueuePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerLeftQueuePayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerLeftQueuePayload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlayerLeftQueuePayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlayerLeftQueuePayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlayerLeftQueuePayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MatchCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Players       []*MatchPlayer         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	GameServer    *GameServer            `protobuf:"bytes,3,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	LobbyId       string                 `protobuf:"bytes,4,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GameId        string                 `protobuf:"bytes,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // For server allocation queue (FIFO per game/region).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCreatedPayload) Reset() {
	*x = MatchCreatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreatedPayload) ProtoMessage() {}

func (x *MatchCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreatedPayload.ProtoReflect.Descriptor instead.
func (*MatchCreatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{9}
}

func (x *MatchCreatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCreatedPayload) GetPlayers() []*MatchPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchCreatedPayload) GetGameServer() *GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

func (x *MatchCreatedPayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *MatchCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MatchCreatedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MatchCreatedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MatchPlayer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PartyId             string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"` // Empty if solo.
	ResourcePermissions []string               `protobuf:"bytes,3,rep,name=resource_permissions,json=resourcePermissions,proto3" json:"resource_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchPlayer) Reset() {
	*x = MatchPlayer{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPlayer) ProtoMessage() {}

func (x *MatchPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPlayer.ProtoReflect.Descriptor instead.
func (*MatchPlayer) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{10}
}

func (x *MatchPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MatchPlayer) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *MatchPlayer) GetResourcePermissions() []string {
	if x != nil {
		return x.ResourcePermissions
	}
	return nil
}

type GameServer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ResourceOwnerId string                 `protobuf:"bytes,3,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{11}
}

func (x *GameServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GameServer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GameServer) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

type MatchCompletedPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MatchId            string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIds          []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	WinnerTeamId       string                 `protobuf:"bytes,3,opt,name=winner_team_id,json=winnerTeamId,proto3" json:"winner_team_id,omitempty"` // Empty if draw.
	IsDraw             bool                   `protobuf:"varint,4,opt,name=is_draw,json=isDraw,proto3" json:"is_draw,omitempty"`
	CompletedAtEpochMs int64                  `protobuf:"varint,5,opt,name=completed_at_epoch_ms,json=completedAtEpochMs,proto3" json:"completed_at_epoch_ms,omitempty"`
	TenantId           string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId           string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LobbyId            *string                `protobuf:"bytes,8,opt,name=lobby_id,json=lobbyId,proto3,oneof" json:"lobby_id,omitempty"`               // Optional: for prize distribution; from game server when available.
	PrizePoolId        *string                `protobuf:"bytes,9,opt,name=prize_pool_id,json=prizePoolId,proto3,oneof" json:"prize_pool_id,omitempty"` // Optional: for prize distribution; from lobby when available.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchCompletedPayload) Reset() {
	*x = MatchCompletedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCompletedPayload) ProtoMessage() {}

func (x *MatchCompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCompletedPayload.ProtoReflect.Descriptor instead.
func (*MatchCompletedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{12}
}

func (x *MatchCompletedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCompletedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchCompletedPayload) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

func (x *MatchCompletedPayload) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

func (x *MatchCompletedPayload) GetCompletedAtEpochMs() int64 {
	if x != nil {
		return x.CompletedAtEpochMs
	}
	return 0
}

func (x *MatchCompletedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MatchCompletedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MatchCompletedPayload) GetLobbyId() string {
	if x != nil && x.LobbyId != nil {
		return *x.LobbyId
	}
	return ""
}

func (x *MatchCompletedPayload) GetPrizePoolId() string {
	if x != nil && x.PrizePoolId != nil {
		return *x.PrizePoolId
	}
	return ""
}

type MatchResultsCalculatedPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MatchId             string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIds           []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	WinnerTeamId        string                 `protobuf:"bytes,3,opt,name=winner_team_id,json=winnerTeamId,proto3" json:"winner_team_id,omitempty"` // Empty if draw. For 1v1, may be winning player_id.
	IsDraw              bool                   `protobuf:"varint,4,opt,name=is_draw,json=isDraw,proto3" json:"is_draw,omitempty"`
	CompletedAtEpochMs  int64                  `protobuf:"varint,5,opt,name=completed_at_epoch_ms,json=completedAtEpochMs,proto3" json:"completed_at_epoch_ms,omitempty"`
	CalculatedAtEpochMs int64                  `protobuf:"varint,6,opt,name=calculated_at_epoch_ms,json=calculatedAtEpochMs,proto3" json:"calculated_at_epoch_ms,omitempty"` // When results were calculated (audit).
	TenantId            string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourceOwnerId     string                 `protobuf:"bytes,9,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`
	GameId              *string                `protobuf:"bytes,10,opt,name=game_id,json=gameId,proto3,oneof" json:"game_id,omitempty"`                  // Optional: for per-game ratings; from match creation when available.
	LobbyId             *string                `protobuf:"bytes,11,opt,name=lobby_id,json=lobbyId,proto3,oneof" json:"lobby_id,omitempty"`               // Optional: for prize distribution; from match creation when available.
	PrizePoolId         *string                `protobuf:"bytes,12,opt,name=prize_pool_id,json=prizePoolId,proto3,oneof" json:"prize_pool_id,omitempty"` // Optional: for prize distribution; from lobby when available.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchResultsCalculatedPayload) Reset() {
	*x = MatchResultsCalculatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResultsCalculatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultsCalculatedPayload) ProtoMessage() {}

func (x *MatchResultsCalculatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultsCalculatedPayload.ProtoReflect.Descriptor instead.
func (*MatchResultsCalculatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{13}
}

func (x *MatchResultsCalculatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchResultsCalculatedPayload) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

func (x *MatchResultsCalculatedPayload) GetCompletedAtEpochMs() int64 {
	if x != nil {
		return x.CompletedAtEpochMs
	}
	return 0
}

func (x *MatchResultsCalculatedPayload) GetCalculatedAtEpochMs() int64 {
	if x != nil {
		return x.CalculatedAtEpochMs
	}
	return 0
}

func (x *MatchResultsCalculatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetGameId() string {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetLobbyId() string {
	if x != nil && x.LobbyId != nil {
		return *x.LobbyId
	}
	return ""
}

func (x *MatchResultsCalculatedPayload) GetPrizePoolId() string {
	if x != nil && x.PrizePoolId != nil {
		return *x.PrizePoolId
	}
	return ""
}

type PrizeDistributedPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MatchId              string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerDetails        []*WinnerPrizeDetail   `protobuf:"bytes,2,rep,name=winner_details,json=winnerDetails,proto3" json:"winner_details,omitempty"`                           // player_id, amount_cents, currency per winner.
	DistributedAtEpochMs int64                  `protobuf:"varint,3,opt,name=distributed_at_epoch_ms,json=distributedAtEpochMs,proto3" json:"distributed_at_epoch_ms,omitempty"` // When the event was produced (audit).
	TenantId             string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId             string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourceOwnerId      string                 `protobuf:"bytes,6,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"` // For authorization; wallet API validates before transfer.
	LobbyId              string                 `protobuf:"bytes,7,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`                           // Optional: lobby/tournament reference.
	PrizePoolId          string                 `protobuf:"bytes,8,opt,name=prize_pool_id,json=prizePoolId,proto3" json:"prize_pool_id,omitempty"`             // Optional: prize pool reference.
	Currency             string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`                                        // e.g. "USD" — applies when amounts are uniform.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrizeDistributedPayload) Reset() {
	*x = PrizeDistributedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrizeDistributedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeDistributedPayload) ProtoMessage() {}

func (x *PrizeDistributedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeDistributedPayload.ProtoReflect.Descriptor instead.
func (*PrizeDistributedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{14}
}

func (x *PrizeDistributedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetWinnerDetails() []*WinnerPrizeDetail {
	if x != nil {
		return x.WinnerDetails
	}
	return nil
}

func (x *PrizeDistributedPayload) GetDistributedAtEpochMs() int64 {
	if x != nil {
		return x.DistributedAtEpochMs
	}
	return 0
}

func (x *PrizeDistributedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetPrizePoolId() string {
	if x != nil {
		return x.PrizePoolId
	}
	return ""
}

func (x *PrizeDistributedPayload) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type WinnerPrizeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"` // Prize amount in smallest currency unit (e.g. cents).
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                           // Override per-winner if needed; else use payload-level currency.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinnerPrizeDetail) Reset() {
	*x = WinnerPrizeDetail{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinnerPrizeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnerPrizeDetail) ProtoMessage() {}

func (x *WinnerPrizeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnerPrizeDetail.ProtoReflect.Descriptor instead.
func (*WinnerPrizeDetail) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{15}
}

func (x *WinnerPrizeDetail) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WinnerPrizeDetail) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *WinnerPrizeDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RatingsUpdatedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Deltas           []*PlayerRatingDelta   `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	UpdatedAtEpochMs int64                  `protobuf:"varint,3,opt,name=updated_at_epoch_ms,json=updatedAtEpochMs,proto3" json:"updated_at_epoch_ms,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourceOwnerId  string                 `protobuf:"bytes,6,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"` // For authorization; from MatchResultsCalculated envelope.
	GameId           string                 `protobuf:"bytes,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                              // Optional: ratings per game; empty if not available.
	AuditTrail       *RatingAuditTrail      `protobuf:"bytes,8,opt,name=audit_trail,json=auditTrail,proto3" json:"audit_trail,omitempty"`                  // Algorithm version, reason, updated_by for compliance.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RatingsUpdatedPayload) Reset() {
	*x = RatingsUpdatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingsUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingsUpdatedPayload) ProtoMessage() {}

func (x *RatingsUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingsUpdatedPayload.ProtoReflect.Descriptor instead.
func (*RatingsUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{16}
}

func (x *RatingsUpdatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetDeltas() []*PlayerRatingDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

func (x *RatingsUpdatedPayload) GetUpdatedAtEpochMs() int64 {
	if x != nil {
		return x.UpdatedAtEpochMs
	}
	return 0
}

func (x *RatingsUpdatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetAuditTrail() *RatingAuditTrail {
	if x != nil {
		return x.AuditTrail
	}
	return nil
}

type RatingAuditTrail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmVersion string                 `protobuf:"bytes,1,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"` // e.g. "elo-v1"
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                             // e.g. "match_completion"
	UpdatedBy        string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`                      // e.g. "match-making-api"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RatingAuditTrail) Reset() {
	*x = RatingAuditTrail{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingAuditTrail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingAuditTrail) ProtoMessage() {}

func (x *RatingAuditTrail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingAuditTrail.ProtoReflect.Descriptor instead.
func (*RatingAuditTrail) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{17}
}

func (x *RatingAuditTrail) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *RatingAuditTrail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RatingAuditTrail) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type PlayerRatingDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MmrBefore     int32                  `protobuf:"varint,2,opt,name=mmr_before,json=mmrBefore,proto3" json:"mmr_before,omitempty"`
	MmrAfter      int32                  `protobuf:"varint,3,opt,name=mmr_after,json=mmrAfter,proto3" json:"mmr_after,omitempty"`
	Delta         int32                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRatingDelta) Reset() {
	*x = PlayerRatingDelta{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRatingDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRatingDelta) ProtoMessage() {}

func (x *PlayerRatingDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRatingDelta.ProtoReflect.Descriptor instead.
func (*PlayerRatingDelta) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerRatingDelta) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerRatingDelta) GetMmrBefore() int32 {
	if x != nil {
		return x.MmrBefore
	}
	return 0
}

func (x *PlayerRatingDelta) GetMmrAfter() int32 {
	if x != nil {
		return x.MmrAfter
	}
	return 0
}

func (x *PlayerRatingDelta) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_pkg_infra_events_schemas_matchmaking_events_proto protoreflect.FileDescriptor

const file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc = "" +
	"\n" +
	"1pkg/infra/events/schemas/matchmaking_events.proto\x12\x15matchmaking.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vspecversion\x18\x04 \x01(\tR\vspecversion\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12*\n" +
	"\x11resource_owner_id\x18\a \x01(\tR\x0fresourceOwnerId\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12-\n" +
	"\x12dataschema_version\x18\t \x01(\x05R\x11dataschemaVersion\"\xdc\b\n" +
	"\x10MatchmakingEvent\x12@\n" +
	"\benvelope\x18\x01 \x01(\v2$.matchmaking.events.v1.EventEnvelopeR\benvelope\x12Q\n" +
	"\rplayer_queued\x18\n" +
	" \x01(\v2*.matchmaking.events.v1.PlayerQueuedPayloadH\x00R\fplayerQueued\x12Q\n" +
	"\rmatch_created\x18\v \x01(\v2*.matchmaking.events.v1.MatchCreatedPayloadH\x00R\fmatchCreated\x12W\n" +
	"\x0fmatch_completed\x18\f \x01(\v2,.matchmaking.events.v1.MatchCompletedPayloadH\x00R\x0ematchCompleted\x12W\n" +
	"\x0fratings_updated\x18\r \x01(\v2,.matchmaking.events.v1.RatingsUpdatedPayloadH\x00R\x0eratingsUpdated\x12[\n" +
	"\x11player_left_queue\x18\x0e \x01(\v2-.matchmaking.events.v1.PlayerLeftQueuePayloadH\x00R\x0fplayerLeftQueue\x12j\n" +
	"\x16player_queue_confirmed\x18\x0f \x01(\v22.matchmaking.events.v1.PlayerQueueConfirmedPayloadH\x00R\x14playerQueueConfirmed\x12Z\n" +
	"\x10server_allocated\x18\x10 \x01(\v2-.matchmaking.events.v1.ServerAllocatedPayloadH\x00R\x0fserverAllocated\x12Q\n" +
	"\rmatch_started\x18\x11 \x01(\v2*.matchmaking.events.v1.MatchStartedPayloadH\x00R\fmatchStarted\x12p\n" +
	"\x18match_results_calculated\x18\x12 \x01(\v24.matchmaking.events.v1.MatchResultsCalculatedPayloadH\x00R\x16matchResultsCalculated\x12]\n" +
	"\x11prize_distributed\x18\x13 \x01(\v2..matchmaking.events.v1.PrizeDistributedPayloadH\x00R\x10prizeDistributed\x12]\n" +
	"\x11analytics_tracked\x18\x14 \x01(\v2..matchmaking.events.v1.AnalyticsTrackedPayloadH\x00R\x10analyticsTrackedB\x06\n" +
	"\x04data\"\xd3\x03\n" +
	"\x17AnalyticsTrackedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12$\n" +
	"\x0ewinner_team_id\x18\x03 \x01(\tR\fwinnerTeamId\x12\x17\n" +
	"\ais_draw\x18\x04 \x01(\bR\x06isDraw\x121\n" +
	"\x15completed_at_epoch_ms\x18\x05 \x01(\x03R\x12completedAtEpochMs\x12-\n" +
	"\x13tracked_at_epoch_ms\x18\x06 \x01(\x03R\x10trackedAtEpochMs\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\t \x01(\tR\bclientId\x12*\n" +
	"\x11resource_owner_id\x18\n" +
	" \x01(\tR\x0fresourceOwnerId\x12\x17\n" +
	"\agame_id\x18\v \x01(\tR\x06gameId\x12\x19\n" +
	"\blobby_id\x18\f \x01(\tR\alobbyId\x12\"\n" +
	"\rprize_pool_id\x18\r \x01(\tR\vprizePoolId\"\x9e\x02\n" +
	"\x13MatchStartedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12*\n" +
	"\x11resource_owner_id\x18\x02 \x01(\tR\x0fresourceOwnerId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\tR\tplayerIds\x120\n" +
	"\x11countdown_seconds\x18\x04 \x01(\x05H\x00R\x10countdownSeconds\x88\x01\x01\x12<\n" +
	"\x18start_timestamp_epoch_ms\x18\x05 \x01(\x03H\x01R\x15startTimestampEpochMs\x88\x01\x01B\x14\n" +
	"\x12_countdown_secondsB\x1b\n" +
	"\x19_start_timestamp_epoch_ms\"\xb7\x02\n" +
	"\x16ServerAllocatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12*\n" +
	"\x11resource_owner_id\x18\x04 \x01(\tR\x0fresourceOwnerId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x05 \x03(\tR\tplayerIds\x12*\n" +
	"\x0econnection_url\x18\x06 \x01(\tH\x00R\rconnectionUrl\x88\x01\x01\x12.\n" +
	"\x10connection_token\x18\a \x01(\tH\x01R\x0fconnectionToken\x88\x01\x01B\x11\n" +
	"\x0f_connection_urlB\x13\n" +
	"\x11_connection_token\"\x8e\x02\n" +
	"\x1bPlayerQueueConfirmedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1f\n" +
	"\veta_seconds\x18\x05 \x01(\x05R\n" +
	"etaSeconds\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12*\n" +
	"\x11resource_owner_id\x18\b \x01(\tR\x0fresourceOwnerId\"\xe8\x02\n" +
	"\x13PlayerQueuedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12G\n" +
	"\vskill_range\x18\x04 \x01(\v2!.matchmaking.events.v1.SkillRangeH\x00R\n" +
	"skillRange\x88\x01\x01\x12*\n" +
	"\x0epriority_boost\x18\x05 \x01(\x05H\x01R\rpriorityBoost\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x121\n" +
	"\x14resource_permissions\x18\b \x03(\tR\x13resourcePermissionsB\x0e\n" +
	"\f_skill_rangeB\x11\n" +
	"\x0f_priority_boost\">\n" +
	"\n" +
	"SkillRange\x12\x17\n" +
	"\amin_mmr\x18\x01 \x01(\x05R\x06minMmr\x12\x17\n" +
	"\amax_mmr\x18\x02 \x01(\x05R\x06maxMmr\"\xb8\x01\n" +
	"\x16PlayerLeftQueuePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xa0\x02\n" +
	"\x13MatchCreatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12<\n" +
	"\aplayers\x18\x02 \x03(\v2\".matchmaking.events.v1.MatchPlayerR\aplayers\x12B\n" +
	"\vgame_server\x18\x03 \x01(\v2!.matchmaking.events.v1.GameServerR\n" +
	"gameServer\x12\x19\n" +
	"\blobby_id\x18\x04 \x01(\tR\alobbyId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x17\n" +
	"\agame_id\x18\a \x01(\tR\x06gameId\"x\n" +
	"\vMatchPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x121\n" +
	"\x14resource_permissions\x18\x03 \x03(\tR\x13resourcePermissions\"m\n" +
	"\n" +
	"GameServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12*\n" +
	"\x11resource_owner_id\x18\x03 \x01(\tR\x0fresourceOwnerId\"\xe5\x02\n" +
	"\x15MatchCompletedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12$\n" +
	"\x0ewinner_team_id\x18\x03 \x01(\tR\fwinnerTeamId\x12\x17\n" +
	"\ais_draw\x18\x04 \x01(\bR\x06isDraw\x121\n" +
	"\x15completed_at_epoch_ms\x18\x05 \x01(\x03R\x12completedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12\x1e\n" +
	"\blobby_id\x18\b \x01(\tH\x00R\alobbyId\x88\x01\x01\x12'\n" +
	"\rprize_pool_id\x18\t \x01(\tH\x01R\vprizePoolId\x88\x01\x01B\v\n" +
	"\t_lobby_idB\x10\n" +
	"\x0e_prize_pool_id\"\xf8\x03\n" +
	"\x1dMatchResultsCalculatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12$\n" +
	"\x0ewinner_team_id\x18\x03 \x01(\tR\fwinnerTeamId\x12\x17\n" +
	"\ais_draw\x18\x04 \x01(\bR\x06isDraw\x121\n" +
	"\x15completed_at_epoch_ms\x18\x05 \x01(\x03R\x12completedAtEpochMs\x123\n" +
	"\x16calculated_at_epoch_ms\x18\x06 \x01(\x03R\x13calculatedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12*\n" +
	"\x11resource_owner_id\x18\t \x01(\tR\x0fresourceOwnerId\x12\x1c\n" +
	"\agame_id\x18\n" +
	" \x01(\tH\x00R\x06gameId\x88\x01\x01\x12\x1e\n" +
	"\blobby_id\x18\v \x01(\tH\x01R\alobbyId\x88\x01\x01\x12'\n" +
	"\rprize_pool_id\x18\f \x01(\tH\x02R\vprizePoolId\x88\x01\x01B\n" +
	"\n" +
	"\b_game_idB\v\n" +
	"\t_lobby_idB\x10\n" +
	"\x0e_prize_pool_id\"\xfd\x02\n" +
	"\x17PrizeDistributedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12O\n" +
	"\x0ewinner_details\x18\x02 \x03(\v2(.matchmaking.events.v1.WinnerPrizeDetailR\rwinnerDetails\x125\n" +
	"\x17distributed_at_epoch_ms\x18\x03 \x01(\x03R\x14distributedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12*\n" +
	"\x11resource_owner_id\x18\x06 \x01(\tR\x0fresourceOwnerId\x12\x19\n" +
	"\blobby_id\x18\a \x01(\tR\alobbyId\x12\"\n" +
	"\rprize_pool_id\x18\b \x01(\tR\vprizePoolId\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\"o\n" +
	"\x11WinnerPrizeDetail\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xec\x02\n" +
	"\x15RatingsUpdatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12@\n" +
	"\x06deltas\x18\x02 \x03(\v2(.matchmaking.events.v1.PlayerRatingDeltaR\x06deltas\x12-\n" +
	"\x13updated_at_epoch_ms\x18\x03 \x01(\x03R\x10updatedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12*\n" +
	"\x11resource_owner_id\x18\x06 \x01(\tR\x0fresourceOwnerId\x12\x17\n" +
	"\agame_id\x18\a \x01(\tR\x06gameId\x12H\n" +
	"\vaudit_trail\x18\b \x01(\v2'.matchmaking.events.v1.RatingAuditTrailR\n" +
	"auditTrail\"v\n" +
	"\x10RatingAuditTrail\x12+\n" +
	"\x11algorithm_version\x18\x01 \x01(\tR\x10algorithmVersion\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\"\x82\x01\n" +
	"\x11PlayerRatingDelta\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"mmr_before\x18\x02 \x01(\x05R\tmmrBefore\x12\x1b\n" +
	"\tmmr_after\x18\x03 \x01(\x05R\bmmrAfter\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x05R\x05deltaBJZHgithub.com/leet-gaming/match-making-api/pkg/infra/events/schemas;schemasb\x06proto3"

var (
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescOnce sync.Once
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData []byte
)

func file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP() []byte {
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescOnce.Do(func() {
		file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc), len(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc)))
	})
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData
}

var file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),                 // 0: matchmaking.events.v1.EventEnvelope
	(*MatchmakingEvent)(nil),              // 1: matchmaking.events.v1.MatchmakingEvent
	(*AnalyticsTrackedPayload)(nil),       // 2: matchmaking.events.v1.AnalyticsTrackedPayload
	(*MatchStartedPayload)(nil),           // 3: matchmaking.events.v1.MatchStartedPayload
	(*ServerAllocatedPayload)(nil),        // 4: matchmaking.events.v1.ServerAllocatedPayload
	(*PlayerQueueConfirmedPayload)(nil),   // 5: matchmaking.events.v1.PlayerQueueConfirmedPayload
	(*PlayerQueuedPayload)(nil),           // 6: matchmaking.events.v1.PlayerQueuedPayload
	(*SkillRange)(nil),                    // 7: matchmaking.events.v1.SkillRange
	(*PlayerLeftQueuePayload)(nil),        // 8: matchmaking.events.v1.PlayerLeftQueuePayload
	(*MatchCreatedPayload)(nil),           // 9: matchmaking.events.v1.MatchCreatedPayload
	(*MatchPlayer)(nil),                   // 10: matchmaking.events.v1.MatchPlayer
	(*GameServer)(nil),                    // 11: matchmaking.events.v1.GameServer
	(*MatchCompletedPayload)(nil),         // 12: matchmaking.events.v1.MatchCompletedPayload
	(*MatchResultsCalculatedPayload)(nil), // 13: matchmaking.events.v1.MatchResultsCalculatedPayload
	(*PrizeDistributedPayload)(nil),       // 14: matchmaking.events.v1.PrizeDistributedPayload
	(*WinnerPrizeDetail)(nil),             // 15: matchmaking.events.v1.WinnerPrizeDetail
	(*RatingsUpdatedPayload)(nil),         // 16: matchmaking.events.v1.RatingsUpdatedPayload
	(*RatingAuditTrail)(nil),              // 17: matchmaking.events.v1.RatingAuditTrail
	(*PlayerRatingDelta)(nil),             // 18: matchmaking.events.v1.PlayerRatingDelta
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs = []int32{
	19, // 0: matchmaking.events.v1.EventEnvelope.time:type_name -> google.protobuf.Timestamp
	0,  // 1: matchmaking.events.v1.MatchmakingEvent.envelope:type_name -> matchmaking.events.v1.EventEnvelope
	6,  // 2: matchmaking.events.v1.MatchmakingEvent.player_queued:type_name -> matchmaking.events.v1.PlayerQueuedPayload
	9,  // 3: matchmaking.events.v1.MatchmakingEvent.match_created:type_name -> matchmaking.events.v1.MatchCreatedPayload
	12, // 4: matchmaking.events.v1.MatchmakingEvent.match_completed:type_name -> matchmaking.events.v1.MatchCompletedPayload
	16, // 5: matchmaking.events.v1.MatchmakingEvent.ratings_updated:type_name -> matchmaking.events.v1.RatingsUpdatedPayload
	8,  // 6: matchmaking.events.v1.MatchmakingEvent.player_left_queue:type_name -> matchmaking.events.v1.PlayerLeftQueuePayload
	5,  // 7: matchmaking.events.v1.MatchmakingEvent.player_queue_confirmed:type_name -> matchmaking.events.v1.PlayerQueueConfirmedPayload
	4,  // 8: matchmaking.events.v1.MatchmakingEvent.server_allocated:type_name -> matchmaking.events.v1.ServerAllocatedPayload
	3,  // 9: matchmaking.events.v1.MatchmakingEvent.match_started:type_name -> matchmaking.events.v1.MatchStartedPayload
	13, // 10: matchmaking.events.v1.MatchmakingEvent.match_results_calculated:type_name -> matchmaking.events.v1.MatchResultsCalculatedPayload
	14, // 11: matchmaking.events.v1.MatchmakingEvent.prize_distributed:type_name -> matchmaking.events.v1.PrizeDistributedPayload
	2,  // 12: matchmaking.events.v1.MatchmakingEvent.analytics_tracked:type_name -> matchmaking.events.v1.AnalyticsTrackedPayload
	7,  // 13: matchmaking.events.v1.PlayerQueuedPayload.skill_range:type_name -> matchmaking.events.v1.SkillRange
	10, // 14: matchmaking.events.v1.MatchCreatedPayload.players:type_name -> matchmaking.events.v1.MatchPlayer
	11, // 15: matchmaking.events.v1.MatchCreatedPayload.game_server:type_name -> matchmaking.events.v1.GameServer
	15, // 16: matchmaking.events.v1.PrizeDistributedPayload.winner_details:type_name -> matchmaking.events.v1.WinnerPrizeDetail
	18, // 17: matchmaking.events.v1.RatingsUpdatedPayload.deltas:type_name -> matchmaking.events.v1.PlayerRatingDelta
	17, // 18: matchmaking.events.v1.RatingsUpdatedPayload.audit_trail:type_name -> matchmaking.events.v1.RatingAuditTrail
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_infra_events_schemas_matchmaking_events_proto_init() }
func file_pkg_infra_events_schemas_matchmaking_events_proto_init() {
	if File_pkg_infra_events_schemas_matchmaking_events_proto != nil {
		return
	}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1].OneofWrappers = []any{
		(*MatchmakingEvent_PlayerQueued)(nil),
		(*MatchmakingEvent_MatchCreated)(nil),
		(*MatchmakingEvent_MatchCompleted)(nil),
		(*MatchmakingEvent_RatingsUpdated)(nil),
		(*MatchmakingEvent_PlayerLeftQueue)(nil),
		(*MatchmakingEvent_PlayerQueueConfirmed)(nil),
		(*MatchmakingEvent_ServerAllocated)(nil),
		(*MatchmakingEvent_MatchStarted)(nil),
		(*MatchmakingEvent_MatchResultsCalculated)(nil),
		(*MatchmakingEvent_PrizeDistributed)(nil),
		(*MatchmakingEvent_AnalyticsTracked)(nil),
	}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc), len(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes,
		DependencyIndexes: file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs,
		MessageInfos:      file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes,
	}.Build()
	File_pkg_infra_events_schemas_matchmaking_events_proto = out.File
	file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes = nil
	file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs = nil
}
