// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/db/mongodb/game_mongodb.go
//
// Generated by this command:
//
//	mockgen -source=pkg/infra/db/mongodb/game_mongodb.go -destination=test/mocks/game_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	common "github.com/leet-gaming/match-making-api/pkg/common"
	entities "github.com/leet-gaming/match-making-api/pkg/domain/game/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGameWriter is a mock of GameWriter interface.
type MockGameWriter struct {
	ctrl     *gomock.Controller
	recorder *MockGameWriterMockRecorder
	isgomock struct{}
}

// MockGameWriterMockRecorder is the mock recorder for MockGameWriter.
type MockGameWriterMockRecorder struct {
	mock *MockGameWriter
}

// NewMockGameWriter creates a new mock instance.
func NewMockGameWriter(ctrl *gomock.Controller) *MockGameWriter {
	mock := &MockGameWriter{ctrl: ctrl}
	mock.recorder = &MockGameWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameWriter) EXPECT() *MockGameWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameWriter) Create(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameWriterMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameWriter)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameWriter)(nil).Delete), ctx, id)
}

// Put mocks base method.
func (m *MockGameWriter) Put(ctx context.Context, gameID uuid.UUID, game *entities.Game) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockGameWriterMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockGameWriter)(nil).Put), ctx, gameID, game)
}

// Update mocks base method.
func (m *MockGameWriter) Update(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameWriterMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameWriter)(nil).Update), ctx, game)
}

// MockGameReader is a mock of GameReader interface.
type MockGameReader struct {
	ctrl     *gomock.Controller
	recorder *MockGameReaderMockRecorder
	isgomock struct{}
}

// MockGameReaderMockRecorder is the mock recorder for MockGameReader.
type MockGameReaderMockRecorder struct {
	mock *MockGameReader
}

// NewMockGameReader creates a new mock instance.
func NewMockGameReader(ctrl *gomock.Controller) *MockGameReader {
	mock := &MockGameReader{ctrl: ctrl}
	mock.recorder = &MockGameReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameReader) EXPECT() *MockGameReaderMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockGameReader) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockGameReaderMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockGameReader)(nil).Compile), ctx, searchParams, resultOptions)
}

// GetByID mocks base method.
func (m *MockGameReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockGameReader) Search(ctx context.Context, s common.Search) ([]*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameReaderMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameReader)(nil).Search), ctx, s)
}

// MockGameRepository is a mock of GameRepository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockGameRepository) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockGameRepositoryMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockGameRepository)(nil).Compile), ctx, searchParams, resultOptions)
}

// Create mocks base method.
func (m *MockGameRepository) Create(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockGameRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameRepository)(nil).GetByID), ctx, id)
}

// Put mocks base method.
func (m *MockGameRepository) Put(ctx context.Context, gameID uuid.UUID, game *entities.Game) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockGameRepositoryMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockGameRepository)(nil).Put), ctx, gameID, game)
}

// Search mocks base method.
func (m *MockGameRepository) Search(ctx context.Context, s common.Search) ([]*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameRepositoryMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameRepository)(nil).Search), ctx, s)
}

// Update mocks base method.
func (m *MockGameRepository) Update(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameRepositoryMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameRepository)(nil).Update), ctx, game)
}
