// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/db/mongodb/game_mode_mongodb.go
//
// Generated by this command:
//
//	mockgen -source=pkg/infra/db/mongodb/game_mode_mongodb.go -destination=test/mocks/game_mode_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	common "github.com/leet-gaming/match-making-api/pkg/common"
	entities "github.com/leet-gaming/match-making-api/pkg/domain/game/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGameModeWriter is a mock of GameModeWriter interface.
type MockGameModeWriter struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeWriterMockRecorder
	isgomock struct{}
}

// MockGameModeWriterMockRecorder is the mock recorder for MockGameModeWriter.
type MockGameModeWriterMockRecorder struct {
	mock *MockGameModeWriter
}

// NewMockGameModeWriter creates a new mock instance.
func NewMockGameModeWriter(ctrl *gomock.Controller) *MockGameModeWriter {
	mock := &MockGameModeWriter{ctrl: ctrl}
	mock.recorder = &MockGameModeWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeWriter) EXPECT() *MockGameModeWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameModeWriter) Create(ctx context.Context, game *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameModeWriterMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameModeWriter)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameModeWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameModeWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameModeWriter)(nil).Delete), ctx, id)
}

// Put mocks base method.
func (m *MockGameModeWriter) Put(ctx context.Context, gameID uuid.UUID, game *entities.GameMode) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockGameModeWriterMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockGameModeWriter)(nil).Put), ctx, gameID, game)
}

// Update mocks base method.
func (m *MockGameModeWriter) Update(ctx context.Context, game *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameModeWriterMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameModeWriter)(nil).Update), ctx, game)
}

// MockGameModeReader is a mock of GameModeReader interface.
type MockGameModeReader struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeReaderMockRecorder
	isgomock struct{}
}

// MockGameModeReaderMockRecorder is the mock recorder for MockGameModeReader.
type MockGameModeReaderMockRecorder struct {
	mock *MockGameModeReader
}

// NewMockGameModeReader creates a new mock instance.
func NewMockGameModeReader(ctrl *gomock.Controller) *MockGameModeReader {
	mock := &MockGameModeReader{ctrl: ctrl}
	mock.recorder = &MockGameModeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeReader) EXPECT() *MockGameModeReaderMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockGameModeReader) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockGameModeReaderMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockGameModeReader)(nil).Compile), ctx, searchParams, resultOptions)
}

// GetByID mocks base method.
func (m *MockGameModeReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameModeReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameModeReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockGameModeReader) Search(ctx context.Context, s common.Search) ([]*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameModeReaderMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameModeReader)(nil).Search), ctx, s)
}

// MockGameModeRepository is a mock of GameModeRepository interface.
type MockGameModeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeRepositoryMockRecorder
	isgomock struct{}
}

// MockGameModeRepositoryMockRecorder is the mock recorder for MockGameModeRepository.
type MockGameModeRepositoryMockRecorder struct {
	mock *MockGameModeRepository
}

// NewMockGameModeRepository creates a new mock instance.
func NewMockGameModeRepository(ctrl *gomock.Controller) *MockGameModeRepository {
	mock := &MockGameModeRepository{ctrl: ctrl}
	mock.recorder = &MockGameModeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeRepository) EXPECT() *MockGameModeRepositoryMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockGameModeRepository) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockGameModeRepositoryMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockGameModeRepository)(nil).Compile), ctx, searchParams, resultOptions)
}

// Create mocks base method.
func (m *MockGameModeRepository) Create(ctx context.Context, game *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameModeRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameModeRepository)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameModeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameModeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameModeRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockGameModeRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameModeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameModeRepository)(nil).GetByID), ctx, id)
}

// Put mocks base method.
func (m *MockGameModeRepository) Put(ctx context.Context, gameID uuid.UUID, game *entities.GameMode) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockGameModeRepositoryMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockGameModeRepository)(nil).Put), ctx, gameID, game)
}

// Search mocks base method.
func (m *MockGameModeRepository) Search(ctx context.Context, s common.Search) ([]*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameModeRepositoryMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameModeRepository)(nil).Search), ctx, s)
}

// Update mocks base method.
func (m *MockGameModeRepository) Update(ctx context.Context, game *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameModeRepositoryMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameModeRepository)(nil).Update), ctx, game)
}
