// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/game/ports/out/cmd.go
//
// Generated by this command:
//
//	mockgen -source=pkg/domain/game/ports/out/cmd.go -destination=test/mocks/port_interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entities "github.com/leet-gaming/match-making-api/pkg/domain/game/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGameWriter is a mock of GameWriter interface.
type MockGameWriter struct {
	ctrl     *gomock.Controller
	recorder *MockGameWriterMockRecorder
	isgomock struct{}
}

// MockGameWriterMockRecorder is the mock recorder for MockGameWriter.
type MockGameWriterMockRecorder struct {
	mock *MockGameWriter
}

// NewMockGameWriter creates a new mock instance.
func NewMockGameWriter(ctrl *gomock.Controller) *MockGameWriter {
	mock := &MockGameWriter{ctrl: ctrl}
	mock.recorder = &MockGameWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameWriter) EXPECT() *MockGameWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameWriter) Create(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameWriterMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameWriter)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameWriter)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockGameWriter) Update(ctx context.Context, game *entities.Game) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameWriterMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameWriter)(nil).Update), ctx, game)
}

// MockGameReader is a mock of GameReader interface.
type MockGameReader struct {
	ctrl     *gomock.Controller
	recorder *MockGameReaderMockRecorder
	isgomock struct{}
}

// MockGameReaderMockRecorder is the mock recorder for MockGameReader.
type MockGameReaderMockRecorder struct {
	mock *MockGameReader
}

// NewMockGameReader creates a new mock instance.
func NewMockGameReader(ctrl *gomock.Controller) *MockGameReader {
	mock := &MockGameReader{ctrl: ctrl}
	mock.recorder = &MockGameReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameReader) EXPECT() *MockGameReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockGameReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockGameReader) Search(ctx context.Context, query any) ([]*entities.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]*entities.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameReaderMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameReader)(nil).Search), ctx, query)
}

// MockGameModeWriter is a mock of GameModeWriter interface.
type MockGameModeWriter struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeWriterMockRecorder
	isgomock struct{}
}

// MockGameModeWriterMockRecorder is the mock recorder for MockGameModeWriter.
type MockGameModeWriterMockRecorder struct {
	mock *MockGameModeWriter
}

// NewMockGameModeWriter creates a new mock instance.
func NewMockGameModeWriter(ctrl *gomock.Controller) *MockGameModeWriter {
	mock := &MockGameModeWriter{ctrl: ctrl}
	mock.recorder = &MockGameModeWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeWriter) EXPECT() *MockGameModeWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameModeWriter) Create(ctx context.Context, gameMode *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gameMode)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameModeWriterMockRecorder) Create(ctx, gameMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameModeWriter)(nil).Create), ctx, gameMode)
}

// Delete mocks base method.
func (m *MockGameModeWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameModeWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameModeWriter)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockGameModeWriter) Update(ctx context.Context, gameMode *entities.GameMode) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, gameMode)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameModeWriterMockRecorder) Update(ctx, gameMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameModeWriter)(nil).Update), ctx, gameMode)
}

// MockGameModeReader is a mock of GameModeReader interface.
type MockGameModeReader struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeReaderMockRecorder
	isgomock struct{}
}

// MockGameModeReaderMockRecorder is the mock recorder for MockGameModeReader.
type MockGameModeReaderMockRecorder struct {
	mock *MockGameModeReader
}

// NewMockGameModeReader creates a new mock instance.
func NewMockGameModeReader(ctrl *gomock.Controller) *MockGameModeReader {
	mock := &MockGameModeReader{ctrl: ctrl}
	mock.recorder = &MockGameModeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeReader) EXPECT() *MockGameModeReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockGameModeReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameModeReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameModeReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockGameModeReader) Search(ctx context.Context, query any) ([]*entities.GameMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]*entities.GameMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGameModeReaderMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGameModeReader)(nil).Search), ctx, query)
}

// MockRegionWriter is a mock of RegionWriter interface.
type MockRegionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRegionWriterMockRecorder
	isgomock struct{}
}

// MockRegionWriterMockRecorder is the mock recorder for MockRegionWriter.
type MockRegionWriterMockRecorder struct {
	mock *MockRegionWriter
}

// NewMockRegionWriter creates a new mock instance.
func NewMockRegionWriter(ctrl *gomock.Controller) *MockRegionWriter {
	mock := &MockRegionWriter{ctrl: ctrl}
	mock.recorder = &MockRegionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionWriter) EXPECT() *MockRegionWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRegionWriter) Create(ctx context.Context, region *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, region)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRegionWriterMockRecorder) Create(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegionWriter)(nil).Create), ctx, region)
}

// Delete mocks base method.
func (m *MockRegionWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRegionWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRegionWriter)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockRegionWriter) Update(ctx context.Context, region *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, region)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRegionWriterMockRecorder) Update(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRegionWriter)(nil).Update), ctx, region)
}

// MockRegionReader is a mock of RegionReader interface.
type MockRegionReader struct {
	ctrl     *gomock.Controller
	recorder *MockRegionReaderMockRecorder
	isgomock struct{}
}

// MockRegionReaderMockRecorder is the mock recorder for MockRegionReader.
type MockRegionReaderMockRecorder struct {
	mock *MockRegionReader
}

// NewMockRegionReader creates a new mock instance.
func NewMockRegionReader(ctrl *gomock.Controller) *MockRegionReader {
	mock := &MockRegionReader{ctrl: ctrl}
	mock.recorder = &MockRegionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionReader) EXPECT() *MockRegionReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockRegionReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRegionReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRegionReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockRegionReader) Search(ctx context.Context, query any) ([]*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRegionReaderMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRegionReader)(nil).Search), ctx, query)
}
