// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/db/mongodb/region_mongodb.go
//
// Generated by this command:
//
//	mockgen -source=pkg/infra/db/mongodb/region_mongodb.go -destination=test/mocks/region_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	common "github.com/leet-gaming/match-making-api/pkg/common"
	entities "github.com/leet-gaming/match-making-api/pkg/domain/game/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRegionWriter is a mock of RegionWriter interface.
type MockRegionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRegionWriterMockRecorder
	isgomock struct{}
}

// MockRegionWriterMockRecorder is the mock recorder for MockRegionWriter.
type MockRegionWriterMockRecorder struct {
	mock *MockRegionWriter
}

// NewMockRegionWriter creates a new mock instance.
func NewMockRegionWriter(ctrl *gomock.Controller) *MockRegionWriter {
	mock := &MockRegionWriter{ctrl: ctrl}
	mock.recorder = &MockRegionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionWriter) EXPECT() *MockRegionWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRegionWriter) Create(ctx context.Context, game *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRegionWriterMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegionWriter)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockRegionWriter) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRegionWriterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRegionWriter)(nil).Delete), ctx, id)
}

// Put mocks base method.
func (m *MockRegionWriter) Put(ctx context.Context, gameID uuid.UUID, game *entities.Region) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRegionWriterMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRegionWriter)(nil).Put), ctx, gameID, game)
}

// Update mocks base method.
func (m *MockRegionWriter) Update(ctx context.Context, game *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRegionWriterMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRegionWriter)(nil).Update), ctx, game)
}

// MockRegionReader is a mock of RegionReader interface.
type MockRegionReader struct {
	ctrl     *gomock.Controller
	recorder *MockRegionReaderMockRecorder
	isgomock struct{}
}

// MockRegionReaderMockRecorder is the mock recorder for MockRegionReader.
type MockRegionReaderMockRecorder struct {
	mock *MockRegionReader
}

// NewMockRegionReader creates a new mock instance.
func NewMockRegionReader(ctrl *gomock.Controller) *MockRegionReader {
	mock := &MockRegionReader{ctrl: ctrl}
	mock.recorder = &MockRegionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionReader) EXPECT() *MockRegionReaderMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockRegionReader) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockRegionReaderMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockRegionReader)(nil).Compile), ctx, searchParams, resultOptions)
}

// GetByID mocks base method.
func (m *MockRegionReader) GetByID(ctx context.Context, id uuid.UUID) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRegionReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRegionReader)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockRegionReader) Search(ctx context.Context, s common.Search) ([]*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRegionReaderMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRegionReader)(nil).Search), ctx, s)
}

// MockRegionRepository is a mock of RegionRepository interface.
type MockRegionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegionRepositoryMockRecorder
	isgomock struct{}
}

// MockRegionRepositoryMockRecorder is the mock recorder for MockRegionRepository.
type MockRegionRepositoryMockRecorder struct {
	mock *MockRegionRepository
}

// NewMockRegionRepository creates a new mock instance.
func NewMockRegionRepository(ctrl *gomock.Controller) *MockRegionRepository {
	mock := &MockRegionRepository{ctrl: ctrl}
	mock.recorder = &MockRegionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionRepository) EXPECT() *MockRegionRepositoryMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockRegionRepository) Compile(ctx context.Context, searchParams []common.SearchAggregation, resultOptions common.SearchResultOptions) (*common.Search, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, searchParams, resultOptions)
	ret0, _ := ret[0].(*common.Search)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockRegionRepositoryMockRecorder) Compile(ctx, searchParams, resultOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockRegionRepository)(nil).Compile), ctx, searchParams, resultOptions)
}

// Create mocks base method.
func (m *MockRegionRepository) Create(ctx context.Context, game *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRegionRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegionRepository)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockRegionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRegionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRegionRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRegionRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRegionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRegionRepository)(nil).GetByID), ctx, id)
}

// Put mocks base method.
func (m *MockRegionRepository) Put(ctx context.Context, gameID uuid.UUID, game *entities.Region) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, gameID, game)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRegionRepositoryMockRecorder) Put(ctx, gameID, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRegionRepository)(nil).Put), ctx, gameID, game)
}

// Search mocks base method.
func (m *MockRegionRepository) Search(ctx context.Context, s common.Search) ([]*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, s)
	ret0, _ := ret[0].([]*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRegionRepositoryMockRecorder) Search(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRegionRepository)(nil).Search), ctx, s)
}

// Update mocks base method.
func (m *MockRegionRepository) Update(ctx context.Context, game *entities.Region) (*entities.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(*entities.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRegionRepositoryMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRegionRepository)(nil).Update), ctx, game)
}
